quickNote/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

quickNote/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

quickNote/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

quickNote/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    # @notes = Note.all.order("created_at DESC")
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

quickNote/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

quickNote/app/helpers/notes_helper.rb
module NotesHelper
end

quickNote/app/helpers/welcome_helper.rb
module WelcomeHelper
end

quickNote/app/views/layouts/application.html.haml
!!!
%html
%head
  %title QuickNote | Your online Notebook
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}/
%body
  %header
    .header_inner
      = link_to image_tag('logo.png'), root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

quickNote/app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

quickNote/app/views/notes/edit.html.haml
.form_wrapper_with_padding
  %h1 Edit Your Note

  = render 'form'

  = link_to "Cancel", note_path

quickNote/app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    - unless @notes.blank?
      - @notes.each do |note|
        %a{ href: (url_for [note]) }
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    - else
      %h2 Add a Note
      %p Looks like you haven't created your first note yet...
      %button= link_to "Create First Note", new_note_path

quickNote/app/views/notes/new.html.haml
.form_wrapper_with_padding
  %h1 Add a New Note

  = render 'form'

quickNote/app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1= @note.title
    %p= simple_format(@note.content)

    .buttons
      = link_to "Edit", edit_note_path(@note), class: "button"
      = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

quickNote/app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 QuickNote
    %p Your online notebook. Never forget an idea again.
    %button= link_to "Sign Up", new_user_registration_path

#testimonial
  .wrapper
    %p.quote "Best tool to save my notes."
    %p.name -Ulises Morales

#callouts
  .callout_inner
    .wrapper
      .callout
        %i.fa.fa-pencil
        %h2 Notes
        %p Bacon ipsum dolor amet tri-tip ground round ham hock fatback cupim andouille biltong. Rump pork chop boudin hamburger turducken, meatloaf pork. Boudin venison strip steak, porchetta cupim doner pork tenderloin.
      .callout
        %i.fa.fa-lightbulb-o
        %h2 Ideas
        %p Bacon ipsum dolor amet tri-tip ground round ham hock fatback cupim andouille biltong. Rump pork chop boudin hamburger turducken, meatloaf pork. Boudin venison strip steak, porchetta cupim doner pork tenderloin.
      .callout
        %i.fa.fa-bolt
        %h2 Execution
        %p Bacon ipsum dolor amet tri-tip ground round ham hock fatback cupim andouille biltong. Rump pork chop boudin hamburger turducken, meatloaf pork. Boudin venison strip steak, porchetta cupim doner pork tenderloin.

#bottom_cta
  .wrapper
    %h2 What are you waiting for???
    %p I want you to sign up right NOW... If you don't I will find you!
    %button= link_to "Click Me!!!", new_user_registration_path

%footer
  %p &copy; Ulises Morales 2017